
export enum BusinessPermissionCodes
{
    ReadMessage = "ReadMessage",
	UpdateMessage = "UpdateMessage",
	InsertMessage = "InsertMessage",
	DeleteMessage = "DeleteMessage",
	ReadNotification = "ReadNotification",
	UpdateNotification = "UpdateNotification",
	InsertNotification = "InsertNotification",
	DeleteNotification = "DeleteNotification",
	ReadUserExtended = "ReadUserExtended",
	UpdateUserExtended = "UpdateUserExtended",
	InsertUserExtended = "InsertUserExtended",
	DeleteUserExtended = "DeleteUserExtended",
	ReadUserExtendedMessage = "ReadUserExtendedMessage",
	UpdateUserExtendedMessage = "UpdateUserExtendedMessage",
	InsertUserExtendedMessage = "InsertUserExtendedMessage",
	DeleteUserExtendedMessage = "DeleteUserExtendedMessage",
	ReadUserExtendedVotingThemeItem = "ReadUserExtendedVotingThemeItem",
	UpdateUserExtendedVotingThemeItem = "UpdateUserExtendedVotingThemeItem",
	InsertUserExtendedVotingThemeItem = "InsertUserExtendedVotingThemeItem",
	DeleteUserExtendedVotingThemeItem = "DeleteUserExtendedVotingThemeItem",
	ReadUserNotification = "ReadUserNotification",
	UpdateUserNotification = "UpdateUserNotification",
	InsertUserNotification = "InsertUserNotification",
	DeleteUserNotification = "DeleteUserNotification",
	ReadVoteType = "ReadVoteType",
	UpdateVoteType = "UpdateVoteType",
	InsertVoteType = "InsertVoteType",
	DeleteVoteType = "DeleteVoteType",
	ReadVotingTheme = "ReadVotingTheme",
	UpdateVotingTheme = "UpdateVotingTheme",
	InsertVotingTheme = "InsertVotingTheme",
	DeleteVotingTheme = "DeleteVotingTheme",
	ReadVotingThemeItem = "ReadVotingThemeItem",
	UpdateVotingThemeItem = "UpdateVotingThemeItem",
	InsertVotingThemeItem = "InsertVotingThemeItem",
	DeleteVotingThemeItem = "DeleteVotingThemeItem",
}


