
export enum BusinessPermissionCodes
{
    ReadMessage = "ReadMessage",
	UpdateMessage = "UpdateMessage",
	InsertMessage = "InsertMessage",
	DeleteMessage = "DeleteMessage",
	ReadNotification = "ReadNotification",
	UpdateNotification = "UpdateNotification",
	InsertNotification = "InsertNotification",
	DeleteNotification = "DeleteNotification",
	ReadUser = "ReadUser",
	UpdateUser = "UpdateUser",
	InsertUser = "InsertUser",
	DeleteUser = "DeleteUser",
	ReadUserMessage = "ReadUserMessage",
	UpdateUserMessage = "UpdateUserMessage",
	InsertUserMessage = "InsertUserMessage",
	DeleteUserMessage = "DeleteUserMessage",
	ReadUserNotification = "ReadUserNotification",
	UpdateUserNotification = "UpdateUserNotification",
	InsertUserNotification = "InsertUserNotification",
	DeleteUserNotification = "DeleteUserNotification",
	ReadUserVotingThemeItem = "ReadUserVotingThemeItem",
	UpdateUserVotingThemeItem = "UpdateUserVotingThemeItem",
	InsertUserVotingThemeItem = "InsertUserVotingThemeItem",
	DeleteUserVotingThemeItem = "DeleteUserVotingThemeItem",
	ReadVoteType = "ReadVoteType",
	UpdateVoteType = "UpdateVoteType",
	InsertVoteType = "InsertVoteType",
	DeleteVoteType = "DeleteVoteType",
	ReadVotingTheme = "ReadVotingTheme",
	UpdateVotingTheme = "UpdateVotingTheme",
	InsertVotingTheme = "InsertVotingTheme",
	DeleteVotingTheme = "DeleteVotingTheme",
	ReadVotingThemeItem = "ReadVotingThemeItem",
	UpdateVotingThemeItem = "UpdateVotingThemeItem",
	InsertVotingThemeItem = "InsertVotingThemeItem",
	DeleteVotingThemeItem = "DeleteVotingThemeItem",
}


